dev-1.x-TCB-protection-for-host: Added TCB Protection for SuSE-11-SP3 using mkinitrd

diff --git a/tcb_protection/tcb_protection_scripts/measure_host b/tcb_protection/tcb_protection_scripts/measure_host
--- a/tcb_protection/tcb_protection_scripts/measure_host
+++ b/tcb_protection/tcb_protection_scripts/measure_host
@@ -1,5 +1,9 @@
 #!/bin/sh
 # initramfs local-premount script for fixrtc
+#%stage: filesystem
+#%depends: resume
+#%programs: /bin/verifier /bin/tpmextend
+#%modules: tpm
 
 os=CUR_OS
 
@@ -9,7 +13,13 @@ then
 	MANIFEST_PATH=${MANIFEST_PATH}
 	PARTITION_INFO=${PARTITION_INFO}
 	ROOT_MOUNT_PATH=${ROOT}
-else
+elif [ $os = "suse"  ]
+then
+	source /config/mount.sh
+	MANIFEST_PATH=${MANIFEST_PATH}
+        PARTITION_INFO=${PARTITION_INFO}
+        ROOT_MOUNT_PATH=${rootdev}
+else 
 	source /lib/dracut-lib.sh
 	MANIFEST_PATH="$(getarg MANIFEST_PATH=)"
 	PARTITION_INFO="$(getarg PARTITION_INFO=)"
@@ -56,6 +66,11 @@ mount_root()
 	#root_mntDev=`echo $root | awk 'BEGIN{FS=":"}{print $2}'`
 	echo $ROOT_MOUNT_PATH
 	mount -t auto $ROOT_MOUNT_PATH $tmp_root
+	if [ $? -eq 0 ] ; then
+		echo "Root mounted successfully"
+	else
+		echo "Root mount failed, waiting for 15 seconds"
+	fi
 	echo "/ Mount COMPLETED"
 }
 
@@ -80,6 +95,11 @@ unmount_partitions()
 
 	#Unmount Root Partition
 	umount $tmp_root
+	if [ $? = 0 ] ; then
+		echo "Unmounted all sucessfully"
+	else
+		echo "ERROR : Cound not unmount root partition"
+	fi
 	echo "Unmount Paritions - COMPLETE"
 
 }
